name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - feature/tests

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      - name: Run Unit Tests
        run: pytest tests/unit

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 10

      - name: Run Integration Tests
        run: pytest tests/integration

