name: Continuous Deployment

on:
  push:
    branches:
      - main
      - criacao-cd-deployment
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build project
      run: |
        echo "Construindo o projeto..."
        # Aqui você pode adicionar o comando real de build, se necessário
        mkdir -p build
        echo "Arquivo de exemplo" > build/exemplo.txt

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ./build  # Diretório onde o artefato será armazenado

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact  # Nome deve ser o mesmo do upload
        path: ./deployed      # Diretório onde o artefato será baixado

    - name: Simulate deployment
      run: |
        echo "Fazendo deploy do artefato..."
        ls ./deployed  # Exibe os arquivos baixados como simulação de deploy
