name: Discord Alerts

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord Notification
      uses: johnnyhuy/actions-discord-git-webhook@main
      with:
        url: ${{ secrets.DISCORD_WEBHOOK }}
        content: 'Novo commit ou PR foi feito no repositório. Verifique as alterações!'
