name: Discord Alerts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Discord Notification
        uses: Ilshidur/action-discord@v1.0.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          args: 'Novo commit ou PR foi feito no repositório.'

