name: Discord Alerts

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Send Discord Notification
      uses: infinioz/notificar-discord@main
      with:
        url: ${{ secrets.DISCORD_WEBHOOK }}
        content: "Novo commit ou PR foi feito no repositório. Verifique as alterações!"
        repo_name: "gabysouzabarbosa/CloudCrafter" # Nome do repositório no formato username/repo
        hide_links: true  # Esconde links na visualização
        color: "#7289da"  # Cor personalizada para a mensagem

