name: Discord Alerts

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Notify discord
      uses: th0th/notify-discord@v0.4.1
      if: ${{ always() }}
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_JOB_NAME: "Build and deploy"
        GITHUB_JOB_STATUS: ${{ job.status }}
