name: Discord Alerts
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Discord Notification
        uses: tarek360/github-discord-action@v2
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: 'GitHub Action'
          avatar-url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          message: "Novo commit ou PR foi feito no repositório."

