name: Docker Build and Run

on:
  push:
    branches:
      - main
      - dock
  pull_request:
    branches:
      - dock

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t cloudcrafter-app .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 cloudcrafter-app

    - name: Wait for container to be ready
      run: sleep 15  # Aguarda 15 segundos antes de executar o curl

     - name: Test Application
      run: |
        curl http://localhost:8000
