name: Python Build

on:
  push:
    branches:
      - main
      - criacao-ci
      - feature/tests
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
     - name: Lint code
      run: |
        pip install flake8
        flake8 .  # Verifica todo o código em busca de problemas de estilo


    - name: Start FastAPI server
      run: |
        nohup uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        sleep 30

    - name: Run Integration Tests
      run: |
        python -m unittest discover -s tests/integration

    - name: Build project
      run: |
        # Substitua esse comando pelo processo de build real do seu projeto
        echo "Construindo o projeto..."
